universe 		        = docker
docker_image 		    = tensorflow/tensorflow:latest-gpu
executable              = runner_custom.sh
error                   = pde.err
log                     = pde.log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 1
request_memory = 4G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue 1
